name: Java CI

on: [workflow_dispatch, push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [17, 21, 22-ea]
        distribution: ['temurin']
      fail-fast: false
      max-parallel: 4
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }} ${{ matrix.distribution }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.distribution }}
      - name: Cache local Maven m2
        uses: actions/cache@v4
        with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-m2
      - name: Install dependencies
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            sudo -E apt-get update
            sudo -E apt-get install -y maven
            sudo -E apt-get install -y openjdk-17-jdk
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            brew update
            brew install maven
            brew install adoptopenjdk17
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            choco install maven
            choco install openjdk-17
          fi
          ./mvnw dependency:resolve -B
      - name: Test with Maven
        run: ./mvnw test -B -V --no-transfer-progress -D"license.skip=true"